Image Tomcat with OpenJDK doesn't have linux/arm/v7
$ docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag ghcr.io/openseedbox/base .
WARNING: No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
[+] Building 3.6s (17/17) FINISHED
 => [internal] load .dockerignore                                                                            0.0s
 => => transferring context: 2B                                                                              0.0s
 => [internal] load build definition from Dockerfile                                                         0.0s
 => => transferring dockerfile: 2.07kB                                                                       0.0s
 => resolve image config for docker.io/docker/dockerfile:1                                                   1.1s
 => [auth] docker/dockerfile:pull token for registry-1.docker.io                                             0.0s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:443aab4ca21183e069e7d8b2dc68006594f40bddf1b1  0.0s
 => => resolve docker.io/docker/dockerfile:1@sha256:443aab4ca21183e069e7d8b2dc68006594f40bddf1b15bbd83f5137  0.0s
 => [linux/arm/v7 internal] load metadata for docker.io/library/debian:bullseye-slim                         2.3s
 => [linux/arm/v7 internal] load metadata for docker.io/library/eclipse-temurin:11-jdk                       0.6s
 => [linux/arm64 internal] load metadata for docker.io/library/eclipse-temurin:11-jdk                        1.9s
 => CANCELED [linux/arm64 internal] load metadata for docker.io/library/tomcat:10.1.0-jre11-openjdk-slim-bu  2.3s
 => ERROR [linux/arm/v7 internal] load metadata for docker.io/library/tomcat:10.1.0-jre11-openjdk-slim-bull  2.3s
 => [linux/arm64 internal] load metadata for docker.io/library/debian:bullseye-slim                          2.3s
 => CANCELED [linux/amd64 internal] load metadata for docker.io/library/debian:bullseye-slim                 2.3s
 => [linux/amd64 internal] load metadata for docker.io/library/eclipse-temurin:11-jdk                        1.9s
 => CANCELED [linux/amd64 internal] load metadata for docker.io/library/tomcat:10.1.0-jre11-openjdk-slim-bu  2.3s
 => [auth] library/debian:pull token for registry-1.docker.io                                                0.0s
 => [auth] library/eclipse-temurin:pull token for registry-1.docker.io                                       0.0s
 => [auth] library/tomcat:pull token for registry-1.docker.io                                                0.0s
------
 > [linux/arm/v7 internal] load metadata for docker.io/library/tomcat:10.1.0-jre11-openjdk-slim-bullseye:
------
Dockerfile:13
--------------------
  11 |
  12 |
  13 | >>> FROM tomcat:10.1.0-jre11-openjdk-slim-bullseye as tomcat
  14 |     # Enable Tomcat HealthCheck endpoint
  15 |     RUN sed -i '/^               pattern=.*/a\\t<Valve className="org.apache.catalina.valves.HealthCheckValve" />' /usr/local/tomcat/conf/server.xml;
--------------------
error: failed to solve: no match for platform in manifest sha256:6534eea7432dbbef2a18f3a931e4786ad113713424380e669a39867d5c7c0176: not found